# Generated by Django 5.1.15 on 2026-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_milestone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='github_commit_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='performance_rating',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent'), ('needs_work', 'Needs Work')], default=None, max_length=16, null=True),
        ),
    ]
