# Generated by Django 5.1.15 on 2026-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_github_commit_info_task_performance_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('developer', 'Developer'), ('frontend', 'Frontend Engineer'), ('backend', 'Backend Engineer'), ('devops', 'DevOps / SRE'), ('qa', 'QA'), ('designer', 'Designer'), ('data', 'Data Engineer'), ('security', 'Security Engineer'), ('writer', 'Technical Writer'), ('viewer', 'Viewer')], default='developer', max_length=32),
        ),
    ]
