"""
Tests for Model Monitoring and Drift Detection
"""

import os
import json
import shutil
import pytest
import numpy as np
from datetime import datetime, timedelta
from fastapi.testclient import TestClient

import app.config as cfg
import app.monitoring as mon
from app.data import get_sample_data
from app.trainer import train
from app.inference import engine
from app.main import app


@pytest.fixture(scope="module", autouse=True)
def setup_test_models(tmp_path_factory):
    """
    Module-level fixture to train a model in a temporary folder,
    ensuring baseline_v1.json exists.
    """
    temp_dir = tmp_path_factory.mktemp("models")
    original_models_dir = cfg.get_settings().MODELS_DIR
    cfg.get_settings().MODELS_DIR = str(temp_dir)

    # Train to generate baseline files
    interactions = get_sample_data()
    train(interactions)

    # Force load models
    engine.is_loaded = False
    engine.load_models()

    yield temp_dir

    cfg.get_settings().MODELS_DIR = original_models_dir


@pytest.fixture(autouse=True)
def isolate_prediction_logs():
    """
    Ensures tests write to a clean predictions log file and restores the
    original predictions.jsonl file (if any exists) after test completion.
    """
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    log_dir = os.path.join(base_dir, "logs")
    log_file = os.path.join(log_dir, "predictions.jsonl")
    backup_file = log_file + ".testbackup"

    # Backup if exists
    has_log = os.path.exists(log_file)
    if has_log:
        shutil.move(log_file, backup_file)
    else:
        os.makedirs(log_dir, exist_ok=True)

    yield log_file

    # Clean up test writes
    if os.path.exists(log_file):
        os.remove(log_file)

    # Restore backup
    if has_log:
        shutil.move(backup_file, log_file)


@pytest.fixture
def client():
    with TestClient(app) as c:
        yield c


# ── 1. PSI Calculation Unit Tests ───────────────────────────────────────

def test_calculate_psi_identical_distribution():
    """If actual matches expected distribution, PSI should be 0 (or close to 0)."""
    expected_pct = [0.1, 0.2, 0.4, 0.2, 0.1]
    bin_edges = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    
    # Generate actual values that fall perfectly into those bins in identical proportions
    actual = np.array(
        [0.5] * 10 + [1.5] * 20 + [2.5] * 40 + [3.5] * 20 + [4.5] * 10
    )
    
    psi = mon.calculate_psi(actual, expected_pct, bin_edges)
    assert round(psi, 3) == 0.0


def test_calculate_psi_shifted_distribution():
    """If actual shifts significantly, PSI should be high (>= 0.2)."""
    expected_pct = [0.2, 0.2, 0.2, 0.2, 0.2]
    bin_edges = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    
    # Shift actual values to fall heavily into the upper bins (4.0 - 5.0)
    actual = np.array(
        [0.5] * 2 + [1.5] * 2 + [2.5] * 6 + [3.5] * 20 + [4.5] * 70
    )
    
    psi = mon.calculate_psi(actual, expected_pct, bin_edges)
    assert psi >= 0.2


# ── 2. Drift Endpoint Integration Tests ───────────────────────────────

def test_drift_endpoint_insufficient_data(client):
    """Should report insufficient data if predictions.jsonl is empty or has too few rows."""
    secret = cfg.get_settings().INTERNAL_SERVICE_SECRET
    
    response = client.get(
        "/api/v1/monitoring/drift",
        headers={"X-Internal-Secret": secret}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "insufficient_data"
    assert "message" in data


def _write_mock_logs(log_file_path, recency_avg, count_avg, n_records=50, stable=False):
    """Helper to populate mock prediction records."""
    now = datetime.utcnow()
    lines = []
    for i in range(n_records):
        if stable:
            # Match the exact baseline distributions generated by trainer.py on get_sample_data()
            interaction_count = 1
            user_role_encoded = 2
            project_member_count = 10
            recency_days = float(i % 30)  # ranges 0-29 just like the mock trainer interactions
        else:
            interaction_count = int(np.random.poisson(count_avg))
            user_role_encoded = int(np.random.choice([1, 2, 3], p=[0.2, 0.6, 0.2]))
            project_member_count = int(np.random.normal(10, 2))
            recency_days = float(np.random.normal(recency_avg, 2))

        log_entry = {
            "timestamp": (now - timedelta(minutes=i)).isoformat(),
            "model_version": "v1",
            "user_id": f"user_{i}",
            "project_id": f"project_{i}",
            "interaction_count": interaction_count,
            "user_role_encoded": user_role_encoded,
            "project_member_count": project_member_count,
            "recency_days": recency_days,
            "svd_score": 4.12,
            "xgb_score": 4.54,
            "hybrid_score": 4.288
        }
        lines.append(json.dumps(log_entry) + "\n")
        
    with open(log_file_path, "w") as f:
        f.writelines(lines)


def test_drift_endpoint_stable(client, isolate_prediction_logs):
    """Verify system is stable when logs match baseline training distributions."""
    secret = cfg.get_settings().INTERNAL_SERVICE_SECRET
    
    # Write mock logs with normal feature behaviors matching baseline exactly
    _write_mock_logs(isolate_prediction_logs, recency_avg=15.0, count_avg=1.0, stable=True)
    
    response = client.get(
        "/api/v1/monitoring/drift",
        headers={"X-Internal-Secret": secret}
    )
    assert response.status_code == 200
    data = response.json()
    
    assert data["status"] == "stable"
    assert data["sample_size"] == 50
    assert "recency_days" in data["metrics"]
    assert data["metrics"]["recency_days"]["status"] in ["stable", "moderate_drift"]


def test_drift_endpoint_drift_detected(client, isolate_prediction_logs, capsys):
    """Verify system flags drift and prints alert warning when feature values drift heavily."""
    secret = cfg.get_settings().INTERNAL_SERVICE_SECRET
    
    # Write mock logs with heavily drifted features
    # (e.g., recency averages 180 days, whereas training baseline average is around ~15 days)
    _write_mock_logs(isolate_prediction_logs, recency_avg=180.0, count_avg=0.1)
    
    response = client.get(
        "/api/v1/monitoring/drift",
        headers={"X-Internal-Secret": secret}
    )
    assert response.status_code == 200
    data = response.json()
    
    assert data["status"] == "drift_detected"
    assert data["metrics"]["recency_days"]["status"] == "significant_drift"
    assert data["metrics"]["recency_days"]["psi"] >= 0.2
    
    # Verify logger alert hook printed message to stdout
    captured = capsys.readouterr()
    assert "[CRITICAL ALERT]" in captured.out
    assert "recency_days" in captured.out


# ── 3. Dashboard Endpoint Integration Tests ───────────────────────────

def test_dashboard_endpoint_empty(client):
    """Verify dashboard reports empty stats when logs file doesn't exist."""
    secret = cfg.get_settings().INTERNAL_SERVICE_SECRET
    
    response = client.get(
        "/api/v1/monitoring/dashboard",
        headers={"X-Internal-Secret": secret}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "empty"
    assert data["total_predictions"] == 0


def test_dashboard_endpoint_active(client, isolate_prediction_logs):
    """Verify dashboard computes aggregations and score distributions from prediction logs."""
    secret = cfg.get_settings().INTERNAL_SERVICE_SECRET
    
    _write_mock_logs(isolate_prediction_logs, recency_avg=10.0, count_avg=1.0, n_records=30)
    
    response = client.get(
        "/api/v1/monitoring/dashboard",
        headers={"X-Internal-Secret": secret}
    )
    assert response.status_code == 200
    data = response.json()
    
    assert data["status"] == "active"
    assert data["total_predictions"] == 30
    assert len(data["recent_predictions"]) == 20  # Limit 20
    
    distributions = data["score_distributions"]
    assert distributions["avg_hybrid_score"] == 4.288
    assert distributions["avg_svd_score"] == 4.12
    assert distributions["avg_xgb_score"] == 4.54
    assert distributions["max_score"] == 4.288
    
    # Verify predictions_by_day holds counts grouped by date
    today_str = datetime.utcnow().strftime("%Y-%m-%d")
    assert today_str in data["predictions_by_day"]
    assert data["predictions_by_day"][today_str] == 30
