import { test, expect } from '@playwright/test';

test.describe('Nexus PM - Critical Path E2E Flow', () => {
  test('should complete the login -> project creation -> AI chat -> cited response flow', async ({ page }) => {
    // ── 1. Visit Login Page ──
    await page.goto('/login');
    await expect(page).toHaveTitle(/Nexus/i);

    // ── 2. Submit Login Credentials ──
    await page.fill('input[id="email"]', 'testuser@nexuspm.io');
    await page.fill('input[id="password"]', 'NexusSecurePass123!');
    await page.click('button[type="submit"]');

    // ── 3. Verify Dashboard Redirect ──
    await expect(page).toHaveURL(/\/dashboard/);
    await expect(page.locator('h1')).toContainText(/Dashboard/i);

    // ── 4. Open Projects View ──
    await page.click('a[href="/projects"]');
    await expect(page.locator('h1')).toContainText(/Projects/i);

    // ── 5. Create a Project ──
    await page.click('button:has-text("New Project")');
    await page.fill('input[placeholder="Project name"]', 'E2E Validation Project');
    await page.fill('textarea[placeholder="Project description"]', 'A project generated by automated Playwright E2E tests.');
    await page.click('button:has-text("Create")');

    // ── 6. Select Created Project ──
    await expect(page.locator('tbody')).toContainText('E2E Validation Project');
    await page.click('text=E2E Validation Project');

    // ── 7. Trigger AI Assistant ──
    await page.click('button[aria-label="Open AI Assistant"]');
    await expect(page.locator('div[id="chat-drawer"]')).toBeVisible();

    // ── 8. Send Query to LangGraph Executor ──
    const chatInput = page.locator('textarea[placeholder*="Ask AI"]');
    await chatInput.fill('What is the project description and created date?');
    await page.click('button[id="send-chat-message"]');

    // ── 9. Verify Response Completion ──
    const lastMessage = page.locator('.chat-message-assistant').last();
    await expect(lastMessage).toContainText(/Validation/i, { timeout: 15000 });
    
    // ── 10. Assert Citation Badges Are Rendered ──
    const citation = lastMessage.locator('.citation-badge');
    await expect(citation).toBeVisible();
    await expect(citation).toContainText('[1]');
  });
});
