# Generated by Django 5.1.15 on 2026-07-20 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_add_milestone_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('goal', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
            options={
                'db_table': 'agile_sprint',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintBacklogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_points', models.FloatField(default=1.0, help_text='Estimated story points')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items', to='agile.sprint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_assignments', to='projects.task')),
            ],
            options={
                'db_table': 'agile_sprint_backlog_item',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='SprintReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('sprint', 'Sprint Review')], default='sprint', max_length=16)),
                ('data', models.JSONField(default=dict)),
                ('pdf_url', models.URLField(blank=True, max_length=512)),
                ('excel_url', models.URLField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='agile.sprint')),
            ],
            options={
                'db_table': 'agile_sprint_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', '-start_date'], name='agile_sprin_project_ff833b_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['is_active', 'is_completed'], name='agile_sprin_is_acti_7bbcda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintbacklogitem',
            unique_together={('sprint', 'task')},
        ),
    ]
