# Generated by Django 5.1.15 on 2026-07-20 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_add_milestone_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(help_text='Repository owner (user or org)', max_length=128)),
                ('name', models.CharField(help_text='Repository name', max_length=128)),
                ('full_name', models.CharField(help_text='owner/name', max_length=256, unique=True)),
                ('installation_id', models.BigIntegerField(blank=True, help_text='GitHub App installation ID', null=True)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repos', to='projects.project')),
            ],
            options={
                'db_table': 'github_repository',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_email', models.CharField(blank=True, max_length=255)),
                ('branch', models.CharField(blank=True, default='main', max_length=255)),
                ('url', models.URLField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_integration.githubrepository')),
            ],
            options={
                'db_table': 'github_commit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GitHubBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latest_sha', models.CharField(blank=True, max_length=64)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('last_commit_message', models.TextField(blank=True)),
                ('last_commit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github_integration.githubrepository')),
            ],
            options={
                'db_table': 'github_branch',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GitHubWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('push', 'Push'), ('pull_request', 'Pull Request'), ('issues', 'Issues'), ('create', 'Branch Create'), ('delete', 'Branch Delete')], max_length=32)),
                ('github_event_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='github_integration.githubrepository')),
            ],
            options={
                'db_table': 'github_webhook_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitTaskMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-detected')], default='auto', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_mappings', to='projects.task')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mappings', to='github_integration.githubcommit')),
            ],
            options={
                'db_table': 'github_commit_task_mapping',
                'unique_together': {('commit', 'task')},
            },
        ),
        migrations.CreateModel(
            name='GitHubPR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], max_length=16)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('head_branch', models.CharField(max_length=255)),
                ('base_branch', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=512)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github_integration.githubrepository')),
            ],
            options={
                'db_table': 'github_pull_request',
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'pr_number')},
            },
        ),
        migrations.AddIndex(
            model_name='githubcommit',
            index=models.Index(fields=['repository', 'branch'], name='github_comm_reposit_1c874a_idx'),
        ),
        migrations.AddIndex(
            model_name='githubcommit',
            index=models.Index(fields=['-timestamp'], name='github_comm_timesta_7aba5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='githubcommit',
            unique_together={('repository', 'sha')},
        ),
        migrations.AlterUniqueTogether(
            name='githubbranch',
            unique_together={('repository', 'name')},
        ),
        migrations.AddIndex(
            model_name='githubwebhookevent',
            index=models.Index(fields=['repository', '-created_at'], name='github_webh_reposit_1ad5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='githubwebhookevent',
            index=models.Index(fields=['processed'], name='github_webh_process_55932b_idx'),
        ),
    ]
