# Generated by Django 5.1.15 on 2026-07-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
